[package]
name = "rugistry"
version = "0.0.0"
edition = "2021"
description = "Rusty registry for developers"
license = "Apache-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.8"

[[bin]]
name = "rugistry"
path = "bin/main.rs"
